[tox]
envlist = py-falcon{3,4},
          no-deps,
          pep8,
          mypy,

[testenv]
setenv=
      falcon4: COV=--cov falcon_auth2
deps =
      -r{toxinidir}/test/requirements.txt
      falcon4: falcon>=4,<5
      falcon4: .[async, jwt]
      falcon3: .[async, jwt]
      falcon3: falcon<4
commands = pytest {env:COV:} test []

[testenv:no-deps]
deps =
      -r{toxinidir}/test/requirements.txt
      falcon>=4,<5
commands = pytest test []

[testenv:pep8]
deps = flake8
commands = flake8 []

[testenv:mypy]
deps = 
      mypy
      types-greenlet
commands = mypy []